# Generated by Django 5.2.5 on 2025-09-11 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='authentication.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='id_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='authentication.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.city'),
        ),
    ]
