# Generated by Django 5.2.5 on 2025-10-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_id_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
